superbag/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
from django.contrib.sitemaps.views import sitemap

from main.views import (
    salepoint, contact, HomePageView, CreateRequest, LostBaggage,
    LostBaggageRu, HomePageViewRu
    )
from main.sitemap import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = patterns(
    '',
    # url(r'^blog/', include('blog.urls')),
    url(
        r'^$',
        HomePageView.as_view(template_name="index.html"),
        name='indexua'),
    url(
        r'^ru$',
        HomePageViewRu.as_view(template_name="ru/index.html"),
        name='indexru'),


    url(r'^lost_baggage/$', LostBaggage.as_view(), name='lost_baggage'),
    url(r'^ru/lost_baggage/$',
        LostBaggageRu.as_view(),
        name='ru_lost_baggage'),

    url(r'^create_request/$', CreateRequest.as_view(), name='create_request'),
    # url(r'^point', SalePointAPI.as_view(), name='salepoints'),
    url(r'^point', salepoint, name='salepoints'),
    url(r'^contact/?$', contact, name='contact'),

    url(r'^verytrickyadmin/', include(admin.site.urls)),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    (r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt')),
)

superbag/main/models.py
# -*- coding: utf-8 -*-

import datetime

from django.db import models


class SalePoint(models.Model):
    TYPE_CHOICES = (
        ('air', 'airport'),
        ('tr', 'train station'),
        ('bus', 'bus station'),
    )

    lon = models.FloatField(null=False, blank=False)
    lat = models.FloatField(null=False, blank=False)
    name = models.CharField(max_length=256, null=False, blank=False)
    address = models.CharField(max_length=512, null=False, blank=False)
    point_type = models.CharField(
        max_length=64, null=False, blank=False, choices=TYPE_CHOICES)

    def __unicode__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=256, blank=False)
    email = models.CharField(max_length=256, blank=False)
    text = models.CharField(max_length=4096, blank=False)
    created = models.DateField(default=datetime.datetime.now)

    def __unicode__(self):
        return u'{} {}'.format(self.name, self.email)


class InsuranceRequest(models.Model):
    author = models.CharField(max_length=256)
    phone = models.CharField(max_length=32)
    email = models.EmailField(max_length=256)
    airport_arrival = models.CharField(max_length=256)
    airport_destination = models.CharField(max_length=256)
    ticket_num = models.CharField(max_length=32)
    created = models.DateField(default=datetime.datetime.now)
    event_date = models.DateField()
    description = models.CharField(max_length=2056)
    info = models.CharField(max_length=2056, blank=True)

    def __unicode__(self):
        return u'{} в {}'.format(self.author, self.event_date)


class SiteFields(models.Model):
    title = models.CharField(max_length=128)
    text = models.CharField(max_length=10000)
    language = models.CharField(max_length=5)

    def __unicode__(self):
        return u'{} {}'.format(self.language, self.title)

templates/base.html
<!DOCTYPE html>
<html lang="uk">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="description" content="Superbag - защита и страховка багажа в аэропортах Киева и всей Украины">
    <meta name="keywords" content="защита багажа, superbag, защита багажа украина, защита багажа киев, страхование багажа, упаковка багажа, упаковка багажа, безопасность багажа, superbag украина, страхование багажа украина">
      <title> Суперзахист вашого багажу </title>
          <link rel="icon" href="{{ STATIC_URL }}image/favicon.ico">
          {% block styles %}
            <link rel="stylesheet" type="text/css" href="{{STATIC_URL}}bower_components/fullpage/jquery.fullPage.css" />
            <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css" />
            <link rel="stylesheet" href="{{ STATIC_URL}}css/icons.css">
            <link rel="stylesheet" href="{{ STATIC_URL}}css/flaticonsoc.css"> 
            <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
          {% endblock %}
          {% block scripts_base %}
            <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
            <script src="{{STATIC_URL}}js/main.js"></script>

            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    </script>
          {% endblock %}
    </head>
    <body>
      {% block content %}
     {% endblock %}
    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load main_filters %}
    {% block scripts_base %}
        {{ block.super }}
        <script type="text/javascript" src="{{STATIC_URL}}bower_components/fullpage/jquery.fullPage.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
    	<script type="text/javascript">
    		$(document).ready(function() { 
    			$('#fullpage').fullpage({
    				anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage', '5thpage', '6thpage', 'lastPage'],
                    sectionsColor : ['#C4F0FF', '#E42C52', '#265780', '#DEDEDE', '#DEDEDE', '#265780'],
    				menu: '#menu',
                    navigation: true,
                    navigationPosition: 'left',
    				scrollingSpeed: 500,
                    css3: false,
                    // resize: true,
                    // responsiveWidth: 900,
                    // responsiveHeight: 900,
                    // verticalCentered: false,
    			});
    		});
    	</script>
    {% endblock %}

    {% block content %}

    <ul id="menu">
        <li class='pull-left lang'><a href="{% url 'indexru' %}">Ru</a></li>
        <li class='pull-left lang'><a href="{% url 'lost_baggage' %}"> Страховий випадок</a></li>
        <img src="/static/image/superlogo.svg">
        <li data-menuanchor="5thpage"><a href="#5thpage">Страхування</a></li>
        <li data-menuanchor="4thpage"><a href="#4thpage">Активацiя</a></li>
        <li data-menuanchor="3rdPage"><a href="#3rdPage">Використання</a></li>
        <li data-menuanchor="secondPage"><a href="#secondPage">Суперзахист</a></li>
        <li data-menuanchor="firstPage"><a href="#firstPage">SUPERBAG</a></li>
        <!-- <li data-menuanchor="5thpage"><a href="#5thpage">Когда использовать</a></li>
    --> </ul>


    <div id="fullpage">
    	<div class="section" id="section0">
            <div class="wrapper">
                <div class="title-box">
                
                    <h1> <span>{{ fields|get_item:'Slide 1 title' |safe}}</span></h1>
                    <p class="main-text"> {{ fields|get_item:'Slide 1 text' |safe}}</p>
                </div>
            </div>
    	</div>

    	<div class="section" id="section1">
			<div class="wrapper">
                <div class="sec1-head">
                    <h1> {{ fields|get_item:'Slide 2 title' |safe}} </h1>
                    <p> {{ fields|get_item:'Slide 2 text' |safe}}
                    </p>
                </div>
                <div class="row">
                    <div class="col-xs-6 col-sm-3 col-md-3">
                        <img src="/static/image/icon1.png">
                         <p>{{ fields|get_item:'Slide 2 item 1' |safe}}</p>
                    </div>
                    <div class="col-xs-6 col-sm-3 col-md-3">
                        <img src="/static/image/icon2.png">
                         <p>{{ fields|get_item:'Slide 2 item 2' |safe}}</p>
                    </div>
                    <div class="col-xs-6 col-sm-3 col-md-3">
                        <img src="/static/image/icon3.png">
                         <p>{{ fields|get_item:'Slide 2 item 3' |safe}}</p>
                    </div>
                    <div class="col-xs-6 col-sm-3 col-md-3">
                        <img src="/static/image/icon4.png">
                         <p>{{ fields|get_item:'Slide 2 item 4' |safe}}</p>
                    </div>
                </div>
            </div>
        </div>
           
        <div class="section" id="section2">
            <div class="wrapper">
                <div class="sec2-head">
                    <h1> {{ fields|get_item:'Slide 3 title' |safe}}</h1> 
                    <p>{{ fields|get_item:'Slide 3 text' |safe}}</p> 
                </div>

                <div class="sec2-body row">
                    <div class="activation col-xs-5 col-md-4">
                        <div class="s-2-b-head">
                            <h1>Активуйте суперзахист у випадку</h1>
                        </div>
                        <table>
                            <tr>
                                <td> <img src="static/image/sm_icons/icon1.png"></td>
                                <td> подорожі </td>
                            </tr>
                            <tr>   
                                <td> <img src="static/image/sm_icons/icon2.png"></td>
                                <td> зворотньої дороги додому</td>
                            </tr>
                            <tr>
                                <td> <img src="static/image/sm_icons/icon3.png"></td>
                                <td> коли залишаєте речі без нагляду</td>
                            </tr>
                            <tr>
                                <td> <img src="static/image/sm_icons/icon4.png"></td>
                                <td> коли здаєте багаж в камеру схову</td>
                            </tr>
                        </table>
                    </div>
                    <div class="guybag col-xs-3 col-md-3">
                        <img class="guybag-img" src="/static/image/guybag1.png">
                    </div>
                    <div class="places col-xs-5 col-md-4">
                        <div class="s-2-b-head">
                            <h1> Використовуйте самостiйно</h1>
                        </div>
                        <table>
                            <tr>
                                <td> вдома </td>
                                <td> <img src="static/image/sm_icons/icon5.png"></td>
                            </tr>
                            <tr>   
                                <td>в готелі</td>
                                <td> <img src="static/image/sm_icons/icon6.png"></td>
                            </tr>
                            <tr>
                                <td>в аеропорті</td>
                                <td> <img src="static/image/sm_icons/icon7.png"></td>
                            </tr>
                            <tr>
                                <td>на вокзалі</td>
                                <td> <img src="static/image/sm_icons/icon8.png"></td>
                            </tr>
                        </table>
                    </div>
                </div>
    		</div>
    	</div>
        <div class="section" id="section3">
            <div class="wrapper">
                <div class="sec3-head">
                    <h1>{{ fields|get_item:'Slide 4 title' |safe}}</h1>
                </div>
                <div class="sec3-body row">                
                    <div class="activation-1 col-xs-5">
                        <img src="static/image/part41.png">
                        <img class="number" src="static/image/number1.png">
                        <p> {{ fields|get_item:'Slide 4 item 1' |safe}}</p>
                    </div>
                    <div class="activation-2 col-xs-5">
                        <img class="act-2-img" src="static/image/part42.png">
                        <img class="number" src="static/image/number2.png">
                            <p>{{ fields|get_item:'Slide 4 item 2' |safe}}</p>
                    </div>
                    <div class="activation-3 col-xs-5">
                        <img src="static/image/part43.png">
                        <img class="number" src="static/image/number3.png">
                        <p> {{ fields|get_item:'Slide 4 item 3' |safe}}</p>
                    </div>
                    <div class="activation-4 col-xs-5">
                        <img src="static/image/part44.png">
                        <img class="number" src="static/image/number4.png">
                        <p>{{ fields|get_item:'Slide 4 item 4' |safe}}</p>
                    </div>
                </div>
    		</div>
    	</div>

        <div class="section" id="section4">
            <div class="sec4-head">
                <h1> {{ fields|get_item:'Slide 5 title' |safe}} </h1>
            </div>

            <div class="wrapper">
                <div class="sec4-body row">
                    <div class="limits col-xs-5 col-sm-4 col-md-3 col-lg-4">
                        {{ fields|get_item:'Slide 5 item 1' |safe}}
                    </div>
                    <div class="sec4-bag col-sm-4 col-xs-5 col-md-3 col-lg-3">
                        <img class="bag-img" src="/static/image/5slidebag.png">
                    </div>
                    <div class="periods col-xs-5 col-sm-4 col-md-3 col-lg-4">
                        {{ fields|get_item:'Slide 5 item 2' |safe}}
                        <img class="zlagoda" src="/static/image/zlagoda.png">
                    </div>
                    <div class="fransize col-xs-12">
                        <h3> Франшиза 0%</h3>
                    </div>
                </div>
            </div>

        </div> 

        <div class="section" id="section5">
            <div class="sec6-head">
                <h1> {{ fields|get_item:'Slide 6 title' |safe}} </h1>
            </div>
            <div class="row">
            <div class="col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2 col-lg-offset-2">
                <div id="map"></div>
            </div>
            <div id="salepoints" class="col-md-4 pull-right">
                <ul>
                    <li>Аеропорт "Жуляни", м. Київ </li>
                    <li>Аеропорт м. Дніпропетровськ </li>
                    <li>Аеропорт м. Запоріжжя </li>
                </ul>
            </div>
            </div>
        </div>
        <div class="section" id="section5">
         <div class="wrapper raw">
            <div class="contact-form col-xs-12 col-sm-5 col-md-5">
                <h1> {{ fields|get_item:'Slide 7 item 1' |safe}}
                </h1>
                 <form>
                    {% csrf_token %}
                    <input class="name" type="text"  placeholder="Ваше iм'я">
                    <input type="text" class="email" placeholder="Ваша пошта">
                    <textarea class="message" type="text" name="text"placeholder="Ваше повiдомлення"></textarea>
                </form>

                <button class="btn-send"><span>Вiдправити</span></button>
            </div>

            <div class="contacts col-xs-12 col-sm-5 col-md-6">
                {{ fields|get_item:'Slide 7 item 2' |safe}}

             </div>
        </div>
             <div class="footer">
                <a href="https://www.facebook.com/superbagua"><span class="flaticon-facebook29"></span></a>
                <a href="https://instagram.com/superbag.ua/"><span class="flaticon-photos12"></span></a>
             </div>
        </div>
    </div>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-68523702-1', 'auto');
      ga('send', 'pageview');

    </script>

{% endblock %}

templates/lost_baggage.html
{% extends 'base.html' %}
{% load main_filters %}
{% load staticfiles %}

{% block scripts_base %}
    {{ block.super }}
    <script type="text/javascript" src="{{STATIC_URL}}js/bootstrap-datepicker.js"></script>
{% endblock %}

{% block styles %}
	{{ block.super }}
	<link rel="stylesheet" href="{{ STATIC_URL }}css/datepicker.css" />
{% endblock %}

{% block content %}
	<ul id="menu">
		<a class="pull-left" href="{% url 'indexua' %}">
			<img src="/static/image/superlogo.svg">
		</a>
	</ul>

	<div id="lost_baggage"class='container m-t-150'>
        <div id="alert-form" class="alert alert-success text-center" role="alert"><h3>Дякуємо за ваше звернення, наш співробітник зв'яжеться із вами найближчим часом</h3></div>

		<div class='col-centered col-xs-12 col-md-8'>
            <h2>Шановний клієнт, якщо у Вас стався страховий випадок із багажем Ви маєте:</h2></div>        <ul>            <li>                1) Звернутися до представників адміністрації аеропорту (відділення «Lost & Found») та скласти Акт про пошкодження або зникнення багажу.             </li>           <li>                2) Якщо відбулося пошкодження або відкриття із крадіжкою частини багажу - обов'язково зафіксувати пошкодження на фото або відео.            </li>           <li>                3) Повідомити нам про подію Ви можете одним із способів:                <ul>                    <li>                    • заповнивши форму повідомлення                         <span id="req-from-but" class="label label-info">ТУТ</span>                     </li>                   <li>                        • листом з описом події на адресу електронної пошти  <a href="mailto:superbag@zlagoda.ua">superbag@zlagoda.ua</a>;                  </li>                     <li>                         • відправивши смс с текстом "SOS xxxxxx" на номер +38 050 477 89 89, де хххххх - унікальний номер Вашого страхування                     </li>               </ul>           </li>           <li>                {% load staticfiles %}              4) Не пізніше 30 днів Вам необхідно надати Заяву на виплату, яку Ви можете завантажити <a href="{% static 'file/form.doc'%}"<span class="label label-info">ТУТ</span></a> або заповнити безпосередньо в офісі страхової компанії, зібравши всі необхідні документи. Перелік документів, необхідних для здійснення виплати, Ви можете побачити в пам'ятці, виданої при страхуванні або ознайомитися з ними на сайті компанії.            </li>       </ul>

    <div class="modal fade bs-example-modal-lg" id="ReqModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                	<button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Вкажіть Ваші дані</h4>
                </div>

                <div class="modal-body">
                    <form>
	                    {% csrf_token %}
                        <dl class="dl-horizontal">
                            <dt> ПІБ </dt>
                            <dd>
                                {{ form.author }}
                            </dd>
                            <dt value="Номер телефона(с номером оператора города)">
                                Номер телефону (з номером оператора чи міста)
                            </dt>
                            <dd> {{ form.phone }}</dd>
                            <dt id="email-label">
                                Email
                            </dt>
                            <dd> {{ form.email }}</dd>
                            <dt>
                                Аеропорт вильоту
                            </dt>
                            <dd> {{ form.airport_arrival }}</dd>
                            <dt>
                                Аеропорт прибуття
                            </dt>
                            <dd> {{ form.airport_destination }}</dd>
                            <dt>
                                Номер страхового талона
                            </dt>
                            <dd> {{ form.ticket_num }}</dd>
                            <dt>
                                Дата польоту
                            </dt>
                            <dd> {{ form.event_date }}</dd>
                            <dt>
                                Короткий опис події
                            </dt>
                            <dd> {{ form.description }}</dd>
                            <dt>
                                Додаткова інформація
                            </dt>
	                        <dd> 
	                        	<textarea id="id_info" class="form-control" type="text" name="info" maxlength="2056"> </textarea>
	                        </dd>
                        </dl>
                    </form>
                </div>
                <div class="modal-footer">
	               	<button id="req-save" class="btn btn-success">Відправити</button>
	            </div>
            </div>
        </div>
    </div>

{% endblock %}